baseURL = 'https://kubajecminek.cz/'
languageCode = 'en-us'
title = 'Kuba Ječmínek'
enableEmoji = true

[params]
  [params.author]
    email = 'kuba@kubajecminek.cz'
    name = 'Jakub Ječmínek'

[services]
  [services.rss]
    limit = 42